# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIWeather.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from pyowm import OWM
from pyowm.commons.exceptions import UnauthorizedError

import config


class Ui_GUIWeather(object):

    def setupUi(self, GUIWeather):
        GUIWeather.setObjectName("GUIWeather")
        GUIWeather.resize(570, 300)
        GUIWeather.setStyleSheet("background-color: #1d2029;\n"
                                "color: #fff;\n"
                                "font-size: 20px;"
        )

        self.centralwidget = QtWidgets.QWidget(GUIWeather)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 281, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                    "    outline: 0;\n"
                                    "    border: 0;\n"
                                    "    background-color: #f07d2b;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: #f28b41;\n"
                                    "}"
        )

        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 281, 41))
        self.lineEdit.setStyleSheet("background-color: #2a303d;\n"
                                    "outline: 0;\n"
                                    "border: 0;"
        )

        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(300, 20, 261, 261))
        self.textEdit.setStyleSheet("background-color: #2a303d;\n"
                                    "outline: 0;\n"
                                    "border: 0;"
        )

        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 270, 281, 21))
        self.label.setStyleSheet("color: #ccc;\n"
                                "font-size: 10px;"
        )

        self.label.setObjectName("label")
        GUIWeather.setCentralWidget(self.centralwidget)

        self.retranslateUi(GUIWeather)
        QtCore.QMetaObject.connectSlotsByName(GUIWeather)

        self.pushButton.clicked.connect(self.define_weather)

    def define_weather(self):
        try:
            owm = OWM(config.API_KEY)
            mgr = owm.weather_manager()

            place = self.lineEdit.text()
            data = mgr.weather_at_place(place)
            weather = data.weather

            self.textEdit.setText(f'Город: {place}\nТемпература: {weather.temperature("celsius")["temp"]}\nВетер: {weather.wind()["speed"]}\nСтатус: {weather.detailed_status}')
        except UnauthorizedError:
            self.textEdit.setText("Invalid API KEY")
        except Exception as e:
            print("Error", e)

    def retranslateUi(self, GUIWeather):
        _translate = QtCore.QCoreApplication.translate

        GUIWeather.setWindowTitle(_translate("GUIWeather", "MainWindow"))

        self.pushButton.setText(_translate("GUIWeather", "Определить"))
        self.lineEdit.setPlaceholderText(_translate("GUIWeather", "Город"))
        self.label.setText(_translate("GUIWeather", "github.com/Fsoky"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    GUIWeather = QtWidgets.QMainWindow()
    ui = Ui_GUIWeather()
    ui.setupUi(GUIWeather)
    GUIWeather.show()
    sys.exit(app.exec_())
